# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for AIVEX Processing Tool (APT).

Usage:
    pyinstaller APT.spec
"""

from PyInstaller.utils.hooks import collect_submodules

block_cipher = None

hidden = (
    collect_submodules("apt")
    + collect_submodules("apt.workers")
    + collect_submodules("apt.dialogs")
    + collect_submodules("apt.widgets")
    + collect_submodules("apt.utils")
)

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('AiV_LOGO.ico', '.'),
        ('apt/resources/AiV_LOGO.ico', 'apt/resources'),
        # Demo images shipped for the Preprocessing panel's "Load Samples"
        # button. Lands under _internal/sample/ in directory builds.
        ('sample', 'sample'),
    ],
    hiddenimports=hidden,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

import os

# Embed file-version metadata into APT.exe when installer/version_info.txt
# exists (generated by installer/build.ps1 from apt/brand.py:APP_VERSION).
# Running plain `pyinstaller APT.spec` without first calling build.ps1 just
# skips the metadata gracefully.
_version_info = 'installer/version_info.txt'
if not os.path.isfile(_version_info):
    _version_info = None

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='APT',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    icon=['AiV_LOGO.ico'],
    version=_version_info,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='APT',
)
