# ---------------------------------------------------------------------------
# AIVEX Processing Tool — installer build orchestrator
#
# Steps:
#   1. Parse APP_VERSION from apt/brand.py (single source of truth).
#   2. Generate installer/version_info.txt for the EXE metadata.
#   3. Run PyInstaller (APT.spec) → dist/APT/.
#   4. Copy mim2color.exe + mim_converter_config.ini next to APT.exe so the
#      directory build works standalone (without the installer).
#   5. Run Inno Setup (iscc) → installer/Output/APT_Setup_v<version>.exe.
#
# Usage:
#     cd installer
#     .\build.ps1                  # full build
#     .\build.ps1 -SkipPyInstaller # skip step 3 (when dist/ is already fresh)
#     .\build.ps1 -SkipInstaller   # skip step 5 (just rebuild EXE)
# ---------------------------------------------------------------------------

[CmdletBinding()]
param(
    [switch]$SkipPyInstaller,
    [switch]$SkipInstaller
)

$ErrorActionPreference = "Stop"

$here        = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $here
$venvPython  = Join-Path $projectRoot "AiV_ProTool\Scripts\python.exe"
$specFile    = Join-Path $projectRoot "APT.spec"
$issFile     = Join-Path $here "APT.iss"
$brandPath   = Join-Path $projectRoot "apt\brand.py"
$versionTxt  = Join-Path $here "version_info.txt"
$distDir     = Join-Path $projectRoot "dist\APT"
$mim2color   = Join-Path $projectRoot "mim2color.exe"
$mimIni      = Join-Path $projectRoot "mim_converter_config.ini"

function Step($name) {
    Write-Host ""
    Write-Host "=== $name ===" -ForegroundColor Cyan
}

# ---- 1. version ----------------------------------------------------------
Step "Reading version from brand.py"
$brandText = Get-Content $brandPath -Raw
if ($brandText -notmatch 'APP_VERSION\s*=\s*"([^"]+)"') {
    throw "Could not parse APP_VERSION from $brandPath"
}
$version       = $matches[1]
$versionParts  = $version.Split(".")
while ($versionParts.Count -lt 4) { $versionParts += "0" }
$versionTuple  = ($versionParts[0..3] -join ",")
Write-Host "Version: $version"
Write-Host "Tuple:   ($versionTuple)"

# ---- 2. version_info.txt -------------------------------------------------
Step "Generating version_info.txt"
$versionInfoBody = @"
# Auto-generated by installer/build.ps1 from apt/brand.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=($versionTuple),
    prodvers=($versionTuple),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName',      u'AIVEX'),
         StringStruct(u'FileDescription',  u'AIVEX Processing Tool'),
         StringStruct(u'FileVersion',      u'$version'),
         StringStruct(u'InternalName',     u'APT'),
         StringStruct(u'LegalCopyright',   u'(c) AIVEX'),
         StringStruct(u'OriginalFilename', u'APT.exe'),
         StringStruct(u'ProductName',      u'AIVEX Processing Tool'),
         StringStruct(u'ProductVersion',   u'$version')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"@
Set-Content -Path $versionTxt -Value $versionInfoBody -Encoding UTF8
Write-Host "Wrote $versionTxt"

# ---- 3. PyInstaller ------------------------------------------------------
if (-not $SkipPyInstaller) {
    Step "Running PyInstaller"
    if (-not (Test-Path $venvPython)) {
        throw "venv python not found at $venvPython"
    }
    Push-Location $projectRoot
    try {
        if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
        if (Test-Path "dist")  { Remove-Item -Recurse -Force "dist" }
        # Redirect stderr→stdout so PyInstaller's WARN lines don't trip
        # PowerShell's NativeCommandError under StrictMode.
        $oldPref = $ErrorActionPreference
        $ErrorActionPreference = "Continue"
        try {
            & $venvPython -m PyInstaller $specFile --noconfirm 2>&1 | ForEach-Object { "$_" }
        } finally {
            $ErrorActionPreference = $oldPref
        }
        if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
    if (-not (Test-Path (Join-Path $distDir "APT.exe"))) {
        throw "PyInstaller did not produce $distDir\APT.exe"
    }
} else {
    Step "Skipping PyInstaller (-SkipPyInstaller)"
}

# ---- 4. Copy external tools next to APT.exe ------------------------------
Step "Copying mim2color.exe + INI into dist\APT"
foreach ($src in @($mim2color, $mimIni)) {
    if (-not (Test-Path $src)) {
        Write-Warning "Missing $src — installer will fail to find it later"
        continue
    }
    Copy-Item $src $distDir -Force
    Write-Host "  + $(Split-Path -Leaf $src)"
}

# ---- 5. Inno Setup compile -----------------------------------------------
if ($SkipInstaller) {
    Step "Skipping Inno Setup (-SkipInstaller)"
    Write-Host "Done. dist\APT\ is ready as a standalone directory build."
    return
}

Step "Locating Inno Setup compiler (iscc.exe)"
$iscc = $null
$onPath = Get-Command iscc.exe -ErrorAction SilentlyContinue
if ($onPath) {
    $iscc = $onPath.Source
} else {
    $candidates = @(
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        "C:\Program Files\Inno Setup 6\ISCC.exe",
        "C:\Program Files (x86)\Inno Setup 5\ISCC.exe"
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { $iscc = $c; break }
    }
}
if (-not $iscc) {
    throw @"
Inno Setup compiler (iscc.exe) not found.
Install from https://jrsoftware.org/isdl.php and re-run.
After install, the compiler is at:
  C:\Program Files (x86)\Inno Setup 6\ISCC.exe
"@
}
Write-Host "Using: $iscc"

Step "Compiling installer"
Push-Location $here
try {
    $oldPref = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        & $iscc "/DMyAppVersion=$version" $issFile 2>&1 | ForEach-Object { "$_" }
    } finally {
        $ErrorActionPreference = $oldPref
    }
    if ($LASTEXITCODE -ne 0) { throw "Inno Setup failed (exit $LASTEXITCODE)" }
} finally {
    Pop-Location
}

$installer = Join-Path $here "Output\APT_Setup_v$version.exe"
if (Test-Path $installer) {
    Write-Host ""
    Write-Host "================================================================" -ForegroundColor Green
    Write-Host "  Installer ready:" -ForegroundColor Green
    Write-Host "  $installer" -ForegroundColor Green
    $size = (Get-Item $installer).Length / 1MB
    Write-Host ("  size: {0:N1} MB" -f $size) -ForegroundColor Green
    Write-Host "================================================================" -ForegroundColor Green
} else {
    throw "Installer not produced at $installer"
}
